git submodule add https://github.com/aralejs/template-arale.git template-arale
git submodule add https://github.com/aralejs/dialog.git dialog
git submodule add https://github.com/aralejs/class.git class
git submodule add https://github.com/aralejs/events.git events
git submodule add https://github.com/aralejs/nico-arale.git nico-arale
git submodule add https://github.com/aralejs/iframe-shim.git iframe-shim
git submodule add https://github.com/aralejs/widget.git widget
git submodule add https://github.com/aralejs/easing.git easing
git submodule add https://github.com/aralejs/fixed.git fixed
git submodule add https://github.com/aralejs/tip.git tip
git submodule add https://github.com/aralejs/popup.git popup
git submodule add https://github.com/aralejs/template-alice.git template-alice
git submodule add https://github.com/aralejs/cookie.git cookie
git submodule add https://github.com/aralejs/messenger.git messenger
git submodule add https://github.com/aralejs/placeholder.git placeholder
git submodule add https://github.com/aralejs/base.git base
git submodule add https://github.com/aralejs/select.git select
git submodule add https://github.com/aralejs/overlay.git overlay
git submodule add https://github.com/aralejs/aralejs.org.git aralejs.org
git submodule add https://github.com/aralejs/validator.git validator
git submodule add https://github.com/aralejs/position.git position
git submodule add https://github.com/aralejs/event-simulate.git event-simulate
git submodule add https://github.com/aralejs/calendar.git calendar
git submodule add https://github.com/aralejs/switchable.git switchable
git submodule add https://github.com/aralejs/autocomplete.git autocomplete
git submodule add https://github.com/aralejs/iframe-uploader.git iframe-uploader
git submodule add https://github.com/aralejs/html5-uploader.git html5-uploader
git submodule add https://github.com/aralejs/404.git 404
git submodule add https://github.com/aralejs/liquidluck-theme-arale2.git liquidluck-theme-arale2
git submodule add https://github.com/aralejs/example-website.git example-website
